# Generated by Django 4.1.7 on 2024-11-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackersusersettings',
            name='notify_types',
            field=models.ManyToManyField(blank=True, null=True, to='api_tracker.notifytype'),
        ),
    ]
