# Generated by Django 4.1.7 on 2024-11-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tracker', '0002_alter_trackersusersettings_notify_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackersusersettings',
            name='notify_types',
            field=models.ManyToManyField(blank=True, to='api_tracker.notifytype'),
        ),
    ]
